package util.enums;

public enum BotState {
    MAIN_MENU,
    REGISTER,
    CHOOSE_CURRENCY,
    COURSE_INFORMATION,
    ADMIN_MENU_SEND,
    CONVERT_CURR,
    INFO_CURR,
    INFO_CURR2,
    CONVERT_TO,
    CONVERT_TO_EDIT,
    CONVERT_TO_EDIT2,
    CONVERT_TO2,
    CONVERT_FROM,
    CONVERT_FROM2,
    CONVERT_SUM,
    CONVERT_INFO,
    ADMIN_MAIN_MENU_SEND,
    GET_EXEL_FILE,
    INFO_CURR_PREV,
    SEND_ADVERTISING
    }
